import {
  LearnerProfile,
  Skill,
  SkillGap,
  CareerRole,
  AssessmentQuestion,
  RoadmapItem,
  Recommendation,
  Badge,
  StudyPartner,
  NotificationItem,
} from '../types';

export const mockUser = {
  id: 'usr_001',
  name: 'Dhanyasakthi',
  email: 'dhanya@pathfinder.ai',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  targetCareer: 'Machine Learning Engineer',
  education: 'B.Tech Computer Science (Senior Year)',
  currentRole: 'Student / Aspiring ML Engineer',
  isDemoAccount: true,
};

export const mockLearnerProfile: LearnerProfile = {
  user: mockUser,
  knowledge: {
    overallMastery: 68,
    conceptsMastered: 14,
    totalConcepts: 22,
    strongSkills: ['Python Fundamentals', 'SQL Data Querying', 'Linear Algebra Basics'],
    weakSkills: ['Model Evaluation Metrics', 'Deep Learning Backpropagation', 'MLOps Pipeline'],
  },
  ability: {
    assessmentAccuracy: 78,
    totalAttempts: 45,
    masteryProgression: +14,
  },
  pace: {
    avgSessionMinutes: 42,
    progressVelocity: 'Optimal',
    estimatedDaysToMastery: 64,
  },
  behavior: {
    sessionsPerWeek: 5,
    completionRate: 86,
    consistencyScore: 92,
    roadmapDelayDays: 0,
  },
  preferences: {
    resourceTypes: ['Interactive', 'Visual', 'Hands-on practice', 'Projects'],
    explanationFormats: ['Code-first', 'Visual Diagram', 'Step-by-step'],
  },
  availability: {
    weeklyHours: 10,
    preferredDays: ['Mon', 'Tue', 'Thu', 'Sat', 'Sun'],
    targetCompletionDate: '2026-11-30',
  },
  lastUpdated: 'Just now (Post Diagnostic Test)',
};

export const mockSkills: Skill[] = [
  {
    id: 'skl_py',
    name: 'Python Foundations',
    category: 'Core Programming',
    currentLevel: 90,
    requiredLevel: 85,
    status: 'mastered',
    prerequisites: [],
    careerRelevance: 'Critical',
  },
  {
    id: 'skl_sql',
    name: 'SQL & Database Design',
    category: 'Data Engineering',
    currentLevel: 85,
    requiredLevel: 75,
    status: 'mastered',
    prerequisites: [],
    careerRelevance: 'High',
  },
  {
    id: 'skl_math',
    name: 'Statistics & Probability',
    category: 'Mathematics',
    currentLevel: 55,
    requiredLevel: 80,
    status: 'needs_reinforcement',
    prerequisites: ['Python Foundations'],
    careerRelevance: 'Critical',
  },
  {
    id: 'skl_ml',
    name: 'Machine Learning Fundamentals',
    category: 'AI & ML',
    currentLevel: 42,
    requiredLevel: 85,
    status: 'in_progress',
    prerequisites: ['Python Foundations', 'Statistics & Probability'],
    careerRelevance: 'Critical',
  },
  {
    id: 'skl_eval',
    name: 'Model Evaluation & Tuning',
    category: 'AI & ML',
    currentLevel: 30,
    requiredLevel: 80,
    status: 'needs_reinforcement',
    prerequisites: ['Machine Learning Fundamentals'],
    careerRelevance: 'High',
  },
  {
    id: 'skl_dl',
    name: 'Deep Learning & Neural Networks',
    category: 'Advanced AI',
    currentLevel: 20,
    requiredLevel: 75,
    status: 'missing',
    prerequisites: ['Machine Learning Fundamentals', 'Model Evaluation & Tuning'],
    careerRelevance: 'High',
  },
  {
    id: 'skl_nlp',
    name: 'NLP & LLMs',
    category: 'Advanced AI',
    currentLevel: 15,
    requiredLevel: 70,
    status: 'missing',
    prerequisites: ['Deep Learning & Neural Networks'],
    careerRelevance: 'Medium',
  },
  {
    id: 'skl_ops',
    name: 'MLOps & Model Deployment',
    category: 'Engineering & Ops',
    currentLevel: 10,
    requiredLevel: 75,
    status: 'locked',
    prerequisites: ['Model Evaluation & Tuning', 'Deep Learning & Neural Networks'],
    careerRelevance: 'Critical',
  },
];

export const mockSkillGaps: SkillGap[] = [
  {
    skillId: 'skl_eval',
    skillName: 'Model Evaluation & Tuning',
    currentLevel: 30,
    requiredLevel: 80,
    gapPriority: 'Critical',
    estimatedHours: 12,
    prerequisites: ['Machine Learning Fundamentals'],
    careerRelevance: 'Essential for ML Engineers to assess overfitting, ROC-AUC, Precision/Recall trade-offs.',
  },
  {
    skillId: 'skl_math',
    skillName: 'Statistics & Probability',
    currentLevel: 55,
    requiredLevel: 80,
    gapPriority: 'High',
    estimatedHours: 10,
    prerequisites: ['Python Foundations'],
    careerRelevance: 'Underpins hypothesis testing, Bayes theorem, and statistical inference in ML.',
  },
  {
    skillId: 'skl_ml',
    skillName: 'Machine Learning Fundamentals',
    currentLevel: 42,
    requiredLevel: 85,
    gapPriority: 'High',
    estimatedHours: 20,
    prerequisites: ['Python Foundations', 'Statistics & Probability'],
    careerRelevance: 'Core competence required for supervised and unsupervised algorithmic modeling.',
  },
  {
    skillId: 'skl_dl',
    skillName: 'Deep Learning & Neural Networks',
    currentLevel: 20,
    requiredLevel: 75,
    gapPriority: 'High',
    estimatedHours: 25,
    prerequisites: ['Machine Learning Fundamentals'],
    careerRelevance: 'Required for computer vision, sequence modeling, and transformer architectures.',
  },
  {
    skillId: 'skl_ops',
    skillName: 'MLOps & Model Deployment',
    currentLevel: 10,
    requiredLevel: 75,
    gapPriority: 'Critical',
    estimatedHours: 18,
    prerequisites: ['Model Evaluation & Tuning'],
    careerRelevance: 'Bridges model experimentation to production REST APIs, Docker, and CI/CD monitoring.',
  },
];

export const mockCareerRoles: CareerRole[] = [
  {
    id: 'car_mle',
    title: 'Machine Learning Engineer',
    description: 'Designs, builds, and deploys production machine learning pipelines and deep learning systems.',
    matchScore: 84,
    readinessScore: 72,
    estimatedMonths: 3,
    salaryRange: '$120,000 - $175,000',
    demandGrowth: '+34% YoY',
    keySkills: [
      { name: 'Python Foundations', required: 85, userProficiency: 90 },
      { name: 'SQL & Database Design', required: 75, userProficiency: 85 },
      { name: 'Statistics & Probability', required: 80, userProficiency: 55 },
      { name: 'Machine Learning Fundamentals', required: 85, userProficiency: 42 },
      { name: 'Model Evaluation & Tuning', required: 80, userProficiency: 30 },
      { name: 'Deep Learning', required: 75, userProficiency: 20 },
      { name: 'MLOps', required: 75, userProficiency: 10 },
    ],
  },
  {
    id: 'car_ds',
    title: 'Data Scientist',
    description: 'Extracts strategic business insights using statistical analysis, predictive modeling, and data story-telling.',
    matchScore: 88,
    readinessScore: 76,
    estimatedMonths: 2.5,
    salaryRange: '$110,000 - $160,000',
    demandGrowth: '+28% YoY',
    keySkills: [
      { name: 'Python Foundations', required: 90, userProficiency: 90 },
      { name: 'SQL & Database Design', required: 85, userProficiency: 85 },
      { name: 'Statistics & Probability', required: 90, userProficiency: 55 },
      { name: 'Machine Learning Fundamentals', required: 80, userProficiency: 42 },
      { name: 'Data Visualization', required: 85, userProficiency: 70 },
      { name: 'Business Analytics', required: 75, userProficiency: 60 },
    ],
  },
  {
    id: 'car_ai',
    title: 'AI Systems Engineer',
    description: 'Specializes in Large Language Models, agentic workflows, vector indexing, and generative AI infrastructure.',
    matchScore: 78,
    readinessScore: 61,
    estimatedMonths: 4,
    salaryRange: '$135,000 - $190,000',
    demandGrowth: '+48% YoY',
    keySkills: [
      { name: 'Python Foundations', required: 90, userProficiency: 90 },
      { name: 'Deep Learning', required: 85, userProficiency: 20 },
      { name: 'NLP & LLMs', required: 85, userProficiency: 15 },
      { name: 'Vector DBs & RAG', required: 80, userProficiency: 10 },
      { name: 'APIs & Microservices', required: 80, userProficiency: 65 },
    ],
  },
  {
    id: 'car_fs',
    title: 'Full Stack Engineer',
    description: 'Builds end-to-end web applications combining frontend UI/UX frameworks and backend REST/GraphQL services.',
    matchScore: 65,
    readinessScore: 68,
    estimatedMonths: 3.5,
    salaryRange: '$105,000 - $155,000',
    demandGrowth: '+22% YoY',
    keySkills: [
      { name: 'Python & Node.js', required: 85, userProficiency: 80 },
      { name: 'Frontend React/TypeScript', required: 80, userProficiency: 60 },
      { name: 'Database & SQL', required: 80, userProficiency: 85 },
      { name: 'System Architecture', required: 75, userProficiency: 40 },
    ],
  },
];

export const mockAssessmentQuestions: AssessmentQuestion[] = [
  {
    id: 'q1',
    skill: 'Python Foundations',
    difficulty: 'Easy',
    question: 'Which Python data structure maintains insertion order and guarantees unique keys?',
    options: ['List', 'Dictionary (Python 3.7+)', 'Set', 'Tuple'],
    correctAnswerIndex: 1,
    explanation: 'Since Python 3.7+, standard dictionaries preserve key insertion order while maintaining fast key uniqueness lookup.',
    conceptTag: 'Data Structures',
  },
  {
    id: 'q2',
    skill: 'Python Foundations',
    difficulty: 'Intermediate',
    question: 'What will be the output of the following list comprehension snippet?',
    codeSnippet: `nums = [1, 2, 3, 4, 5]\nres = [x**2 for x in nums if x % 2 != 0]\nprint(res)`,
    options: ['[1, 4, 9, 16, 25]', '[1, 9, 25]', '[4, 16]', '[1, 3, 5]'],
    correctAnswerIndex: 1,
    explanation: 'The filter `x % 2 != 0` selects odd numbers [1, 3, 5], and squares each value yielding `[1, 9, 25]`.',
    conceptTag: 'List Comprehensions',
  },
  {
    id: 'q3',
    skill: 'Statistics & Probability',
    difficulty: 'Intermediate',
    question: 'When evaluating a binary classifier with high class imbalance (e.g. 99% negative cases), which metric is LEAST informative?',
    options: ['ROC-AUC', 'Precision-Recall AUC', 'Standard Classification Accuracy', 'F1-Score'],
    correctAnswerIndex: 2,
    explanation: 'Standard Accuracy can yield 99% simply by predicting the majority class every time, masking complete failure on the minority target class.',
    conceptTag: 'Evaluation Metrics',
  },
  {
    id: 'q4',
    skill: 'Model Evaluation & Tuning',
    difficulty: 'Intermediate',
    question: 'A Decision Tree model displays 99% training accuracy but only 62% validation accuracy. What phenomenon is occurring?',
    options: ['Underfitting (High Bias)', 'Overfitting (High Variance)', 'Optimal Convergence', 'Data Leakage'],
    correctAnswerIndex: 1,
    explanation: 'A large discrepancy between high training accuracy and low validation accuracy is the classic hallmark of overfitting (High Variance).',
    conceptTag: 'Overfitting vs Underfitting',
  },
  {
    id: 'q5',
    skill: 'Model Evaluation & Tuning',
    difficulty: 'Advanced',
    question: 'In a medical diagnostic test for rare disease detection, which error carries the HIGHEST real-world cost?',
    options: ['False Positive (Type I Error)', 'False Negative (Type II Error)', 'True Positive', 'True Negative'],
    correctAnswerIndex: 1,
    explanation: 'A False Negative means a sick patient is misclassified as healthy and denied critical treatment, which carries extreme severity.',
    conceptTag: 'Confusion Matrix Analysis',
  },
  {
    id: 'q6',
    skill: 'Machine Learning Fundamentals',
    difficulty: 'Intermediate',
    question: 'Which loss function is standard for training a binary logistic regression model?',
    options: ['Mean Squared Error (MSE)', 'Binary Cross-Entropy (Log Loss)', 'Categorical Cross-Entropy', 'Mean Absolute Error (MAE)'],
    correctAnswerIndex: 1,
    explanation: 'Binary Cross-Entropy penalizes wrong high-confidence probability predictions exponentially and is convex for logistic regression.',
    conceptTag: 'Loss Functions',
  },
  {
    id: 'q7',
    skill: 'Machine Learning Fundamentals',
    difficulty: 'Advanced',
    question: 'How does L2 Regularization (Ridge) differ from L1 Regularization (Lasso)?',
    options: [
      'L1 squares weights; L2 takes absolute values',
      'L1 can shrink feature coefficients strictly to zero (feature selection); L2 shrinks coefficients smoothly',
      'L2 performs feature selection; L1 prevents gradient explosion',
      'L1 is used only for neural networks'
    ],
    correctAnswerIndex: 1,
    explanation: 'L1 regularization uses absolute weight penalties, driving non-essential coefficients to zero, creating sparse feature sets.',
    conceptTag: 'Regularization',
  },
  {
    id: 'q8',
    skill: 'Deep Learning & Neural Networks',
    difficulty: 'Intermediate',
    question: 'Why is ReLU (Rectified Linear Unit) favored over Sigmoid activation in hidden layers of deep neural networks?',
    options: [
      'ReLU forces output between 0 and 1',
      'ReLU mitigates the vanishing gradient problem for positive inputs',
      'ReLU is computationally slower but mathematically precise',
      'ReLU is smooth and continuously differentiable everywhere'
    ],
    correctAnswerIndex: 1,
    explanation: 'For positive inputs, ReLU has a constant derivative of 1.0, avoiding the saturating derivative tails of Sigmoid that cause vanishing gradients.',
    conceptTag: 'Activation Functions',
  },
];

export const mockRoadmapItems: RoadmapItem[] = [
  {
    id: 'rd_01',
    title: 'Python Core & Data Wrangling',
    skillName: 'Python Foundations',
    phase: 1,
    phaseTitle: 'Foundations & Data Stack',
    order: 1,
    status: 'completed',
    estimatedHours: 15,
    difficulty: 'Beginner',
    resourcesCount: 6,
    whyPositioned: 'Verified 90% mastery in initial diagnostic. Essential baseline for all ML workflows.',
  },
  {
    id: 'rd_02',
    title: 'SQL & Relational Data Engineering',
    skillName: 'SQL & Database Design',
    phase: 1,
    phaseTitle: 'Foundations & Data Stack',
    order: 2,
    status: 'completed',
    estimatedHours: 12,
    difficulty: 'Beginner',
    resourcesCount: 4,
    whyPositioned: 'Verified 85% mastery. Required for pulling feature sets from production databases.',
  },
  {
    id: 'rd_03',
    title: 'Applied Statistics & Probability for ML',
    skillName: 'Statistics & Probability',
    phase: 2,
    phaseTitle: 'Mathematical & Statistical Rigor',
    order: 3,
    status: 'current',
    estimatedHours: 10,
    difficulty: 'Intermediate',
    resourcesCount: 5,
    whyPositioned: 'Targeted gap: Needed to master hypothesis testing, P-values, and probability distributions for ML model tuning.',
  },
  {
    id: 'rd_04',
    title: 'Supervised Learning & Regression Systems',
    skillName: 'Machine Learning Fundamentals',
    phase: 3,
    phaseTitle: 'Core Machine Learning',
    order: 4,
    status: 'current',
    estimatedHours: 18,
    difficulty: 'Intermediate',
    resourcesCount: 8,
    whyPositioned: 'Direct milestone towards ML Engineer goal. Covers Decision Trees, Random Forests, and Gradient Boosting.',
  },
  {
    id: 'rd_05',
    title: 'Model Evaluation, ROC-AUC & Hyperparameter Tuning',
    skillName: 'Model Evaluation & Tuning',
    phase: 4,
    phaseTitle: 'Model Optimization',
    order: 5,
    status: 'locked',
    estimatedHours: 12,
    difficulty: 'Intermediate',
    resourcesCount: 5,
    whyPositioned: 'High-priority gap flagged during diagnostic assessment. Moved earlier in your adaptive path.',
  },
  {
    id: 'rd_06',
    title: 'Deep Learning & PyTorch Architecture',
    skillName: 'Deep Learning & Neural Networks',
    phase: 5,
    phaseTitle: 'Advanced Deep Learning',
    order: 6,
    status: 'locked',
    estimatedHours: 25,
    difficulty: 'Advanced',
    resourcesCount: 9,
    whyPositioned: 'Prerequisite for Transformer architectures and modern AI systems.',
  },
  {
    id: 'rd_07',
    title: 'Production MLOps, Docker & Fast API Microservice Deployment',
    skillName: 'MLOps & Model Deployment',
    phase: 6,
    phaseTitle: 'Production Deployment',
    order: 7,
    status: 'locked',
    estimatedHours: 20,
    difficulty: 'Advanced',
    resourcesCount: 7,
    whyPositioned: 'Final milestone: Converts raw models into production-ready REST APIs with monitoring.',
  },
];

export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec_01',
    title: 'Precision, Recall & ROC-AUC Deep Dive',
    type: 'Practice',
    skillGapClosed: 'Model Evaluation & Tuning',
    difficulty: 'Intermediate',
    estimatedTime: '45 mins',
    prerequisites: [
      { name: 'Python Foundations', status: 'met' },
      { name: 'Statistics & Probability', status: 'partial' },
    ],
    careerRelevance: 'Critical',
    whyReason: {
      strongSkills: ['Python Foundations', 'SQL Queries'],
      partiallyMastered: ['Statistics'],
      careerRequirement: 'Machine Learning Engineer role requires 80%+ evaluation mastery.',
      recentGapTrigger: 'Your recent diagnostic test showed ambiguity between Type I and Type II error trade-offs.',
    },
    provider: 'PathFinder Interactive Lab',
    rating: 4.9,
  },
  {
    id: 'rec_02',
    title: 'Hands-on Customer Churn Classifier Project',
    type: 'Project',
    skillGapClosed: 'Machine Learning Fundamentals',
    difficulty: 'Intermediate',
    estimatedTime: '3.5 hours',
    prerequisites: [
      { name: 'Python Foundations', status: 'met' },
      { name: 'SQL', status: 'met' },
    ],
    careerRelevance: 'High',
    whyReason: {
      strongSkills: ['Python', 'SQL'],
      partiallyMastered: ['Supervised Learning'],
      careerRequirement: 'Builds portfolio evidence for end-to-end classification pipeline.',
      recentGapTrigger: 'Matches your preferred "Hands-on Projects" learning style.',
    },
    provider: 'PathFinder Capstone Studio',
    rating: 4.8,
  },
  {
    id: 'rec_03',
    title: 'Cross-Validation & Grid Search Optimization',
    type: 'Course',
    skillGapClosed: 'Model Evaluation & Tuning',
    difficulty: 'Intermediate',
    estimatedTime: '2 hours',
    prerequisites: [
      { name: 'Python', status: 'met' },
      { name: 'Statistics', status: 'partial' },
    ],
    careerRelevance: 'High',
    whyReason: {
      strongSkills: ['Python Foundations'],
      partiallyMastered: ['Overfitting Diagnosis'],
      careerRequirement: 'Prevents data leakage in industrial ML models.',
      recentGapTrigger: 'Identified as a high-velocity concept based on your learning speed.',
    },
    provider: 'Scikit-Learn Mastery Series',
    rating: 4.7,
  },
];

export const mockBadges: Badge[] = [
  {
    id: 'bdg_py',
    title: 'Python ML Foundations',
    description: 'Verified 90%+ proficiency in Python data structures, list comprehensions, and vectorized NumPy operations.',
    category: 'Core Engineering',
    masteryPercentage: 90,
    dateEarned: '2026-08-10',
    iconName: 'Code2',
    verifiedByAssessment: true,
    isUnlocked: true,
  },
  {
    id: 'bdg_sql',
    title: 'Relational Data Architect',
    description: 'Demonstrated ability to write complex multi-table joins, subqueries, and window functions for feature engineering.',
    category: 'Data Infrastructure',
    masteryPercentage: 85,
    dateEarned: '2026-08-15',
    iconName: 'Database',
    verifiedByAssessment: true,
    isUnlocked: true,
  },
  {
    id: 'bdg_stats',
    title: 'Statistical Intuition',
    description: 'Demonstrated 75%+ mastery in probability distributions, hypothesis testing, and variance analysis.',
    category: 'Mathematics',
    masteryPercentage: 55,
    iconName: 'LineChart',
    verifiedByAssessment: false,
    isUnlocked: false,
  },
  {
    id: 'bdg_ml',
    title: 'Applied ML Practitioner',
    description: 'Successfully trained, tuned, and evaluated 3 supervised learning models with zero data leakage.',
    category: 'Core AI',
    masteryPercentage: 42,
    iconName: 'Cpu',
    verifiedByAssessment: false,
    isUnlocked: false,
  },
  {
    id: 'bdg_ops',
    title: 'Production MLOps Engineer',
    description: 'Containerized an end-to-end ML model into a FastAPI microservice deployed on cloud infrastructure.',
    category: 'Deployment',
    masteryPercentage: 10,
    iconName: 'Rocket',
    verifiedByAssessment: false,
    isUnlocked: false,
  },
];

export const mockStudyPartners: StudyPartner[] = [
  {
    id: 'prt_01',
    name: 'Aravind Swamy',
    role: 'Aspiring AI Researcher',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    matchPercentage: 94,
    targetCareer: 'Machine Learning Engineer',
    currentFocus: 'Deep Learning & Neural Networks',
    complementarySkills: ['Deep Learning', 'PyTorch', 'Mathematics'],
  },
  {
    id: 'prt_02',
    name: 'Sophia Chen',
    role: 'Data Science Graduate',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    matchPercentage: 89,
    targetCareer: 'Data Scientist',
    currentFocus: 'Model Evaluation & Statistics',
    complementarySkills: ['Statistics & P-Values', 'Data Storytelling', 'R & Python'],
  },
  {
    id: 'prt_03',
    name: 'Marcus Vance',
    role: 'Backend Software Engineer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    matchPercentage: 85,
    targetCareer: 'MLOps Engineer',
    currentFocus: 'Docker & API Infrastructure',
    complementarySkills: ['FastAPI', 'Docker Containerization', 'CI/CD Pipelines'],
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_01',
    title: 'Adaptive Path Recalculated',
    message: 'Based on your diagnostic score, "Model Evaluation & Tuning" has been prioritized in Phase 4 of your roadmap.',
    type: 'adaptive',
    timestamp: '10 mins ago',
    read: false,
    actionUrl: '/roadmap',
  },
  {
    id: 'notif_02',
    title: 'Badge Unlocked!',
    message: 'Congratulations! You earned the "Relational Data Architect" badge with 85% verified mastery.',
    type: 'success',
    timestamp: '2 hours ago',
    read: false,
    actionUrl: '/badges',
  },
  {
    id: 'notif_03',
    title: 'New Partner Match Available',
    message: 'Aravind Swamy has a 94% peer compatibility match for your Machine Learning Engineer track.',
    type: 'info',
    timestamp: '1 day ago',
    read: true,
    actionUrl: '/collaboration',
  },
];
